# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skel < Formula
  desc "Save your Mac dev setup. Restore it anywhere. In minutes."
  homepage "https://github.com/kasperbasse/skel"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/kasperbasse/skel/releases/download/v0.1.0/skel_0.1.0_darwin_amd64.tar.gz"
    sha256 "0f4a671b0eee0c153bb4a94b3a132c143e2b659be7782bb66f13aff3a72dda9c"

    define_method(:install) do
      bin.install "skel"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/kasperbasse/skel/releases/download/v0.1.0/skel_0.1.0_darwin_arm64.tar.gz"
    sha256 "a317271b6e62c61c57c8ae35d05d2fc37d47678cb302212cbb1a7f77ca6c107c"

    define_method(:install) do
      bin.install "skel"
    end
  end
end
